### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by john-light**

### CODE REVIEW

**Comment by sohkai** [comment]
@john-light I've seen this around a few other places... is it a tab character instead of a space?

**Comment by john-light** [comment]
@sohkai idk what the original character was, it looks like a single space in the diff. But I had to backspace and then do a single space again and then the markdown was fixed.

**Comment by izqui** [comment]
This was probably my fault, the spanish keyboard introduces a weird character when space is pressed while pressing ALT.

**Comment by sohkai** [comment]
@izqui Ahhhhh ok now I finally know why some of our READMEs (not sure which ones) don't render properly on Github....

**Pull request merged**
